language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install -y pandoc
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover tests
deploy:
  provider: pypi
  user: "idealista"
  password:
    secure: L80/PUp/eGj6+OPzGfv0vO5V+5V5dIuaw4qRHlVDgEsZaFlJPsEL62x8CYv6DXewaYIBKhMk2cXWMkHuWFKjTcJ+Vjsqx6jIUwBLI48eKAWMxEP3ypJf3gqLeJmYFO6QPUGu1pOuOiFjBeV+yXNz7+C7ZY04cAcvgBGgRs+Tw6Se+AgfWNFXZZDX7N9/eWzFktqRpisWLNUJBBl6JnRcYhiadD5PvqS8eTsI/hiewMWijzlbfzZJ4PEFLJ7g2r3LL2OgHp1FR4zliXo0tMtFSyCFHAYz7vIcGDVlp1GmPSD0Me9h+LnjArK1LwotSA6DdwIVVrS+/ZR3ocHETbUxROrHLLZMN+tE6gcJ+ANq4HTqt4r7WVGO10IOYLqaZmNxazoyYilJRORvpYd6CUpR+8pNybG54YrR4qc4FBoWTob8T1+BGUN6K/R1M2vgZC6adlMmNguNMJ/wX5GzBO7nUju6TcehYJfZQGc3WYQuV/WpE1IHMJSJJwMwAkvJ7yiEM5nj5WDLsrPU6ViBc/konM1Bl/loZ7YhyaKtr9ypqMxkHsnECpAt3gI2Btu4Az8JQd3ZqHgmTmI399E4k1qoRgv0zPjFDDzOM7QB5Q7YZ0jzRBJqFlaII2wZC3iNHfxWSW/bjq9OOwwQkuti/WeyqG2XHg8gwpyixUUqLUw9Wy8=
