language: python
python:
  - '3.5'
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover tests
before_deploy:
  - python3 -m pip install --upgrade setuptools
deploy:
  skip_cleanup: true
  provider: pypi
  user: mchacon
  server: "https://test.pypi.org"
  password:
    secure: "w6pmFslKRY+d+yAU7dwqSQi/B0cZV8aCJ95RurkF1T+q9qcdE62mBsDa2Cc5SU3zrCoS3fC415518fKolbHNToSvx6eePotEh9hSD9bhELEyWAlzD7gwBYuJDs0jj/Gmvi/6AQSTk8UBlM99+IdSUx54KEEyXXVyphPSGvsfrAleq4/Jzpuhs/yGxe0UQ99VAYjGu0hMmZraAUNkFrdw8LY/CztiYPQOmGhZpwPfzF1DpE3zHV8TJiAPCxAFVfmYSeOosSo/UlgUq9HDGwhh8jnE8Bchxb6fX+/VpdCWnI7a5REfIm4Htbe3NNYzHrejlUSS0V6CvcChrBy71efXKdwPVOrIYJ5S9OsMWhuP46tSdgwxsc7QB22exvGc4ipvcw3tJQk5E8dw3Uv9xkjofpZXhg2/LgseNES6f2zyMmPkoUa0+pDarbDBnVUDFwR47tMa/BpSYDvUt0jDzoCNwcHFpLuRTNtXn+r/JEF89wYFyv3i3q6PQRezoGwxnDh/jCWb5HILNJB95PSUw6YnEFGkIH1zQotRQhfVeWxyawuw+v15Fy2blcSbK4rqq8nU/w7qwpr3a83BgsQrwdYpikfQeSZTpq7Cpb7trDyYUChSBzyMR7NpA2qGZKQ5AJzRZg3QyFit5VpHnwJ6bMKBN1Y6DJ00IzCZ1e3ECoxL9g0="
  on:
    branch: bug/pypi_deployment
