# Default values for prom2teams.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resources:
 limits:
   cpu: 200m
   memory: 200Mi
 requests:
   cpu: 100m
   memory: 128Mi

image:
  repository: idealista/prom2teams
  tag: 2.4.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8089

ingress:
  enabled: false

prom2teams:
  host: 0.0.0.0
  port: 8089
  connector: 
  group_alerts_by:
  loglevel: INFO
  templatepath: /opt/prom2teams/helmconfig/teams.j2
  config: /opt/prom2teams/helmconfig/config.ini
